<?php
echo $this->headScript()->
        appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
        appendFile($this->baseUrl() . "/js/bootstrap/bootstrap.js")->
        appendFile($this->baseUrl() . "/js/jquery.validate.js");

echo $this->headLink()
        ->setIndent('  ')
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap.css")
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap-responsive.css");
?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
    <title>Ticketshow</title>
    <style>
        tr,td{
            padding: 10px;
        }
        #logo{margin: 20px;}
        a{
            text-align: right;
            text-decoration: none;
            font-size: 10px;
            color: #49AFCD;
            top: 0;
            float: right;
        }
        #forgot{
            margin: 0;
            padding: 0;
            font-size:11px;
            height: 11px;
            line-height: 11px;
        }
    </style>

    <script type="text/javascript">
        function hideAlert() {
            $("#value-alert").hide(1000);
        }
        $(document).ready(function() {
            setTimeout("hideAlert()", 7500);

            $("#login-form").validate({
                rules: {
                    username: {
                        required: true
                    },
                    password: {
                        required: true
                    }
                },
                messages: {
                    username: "Username requerido",
                    password: "Password requerido"
                }
            });
        });
    </script>

</head>
<div class="span9" style="margin: 30px;">
    <div id="logo">   
        <h1>Ticketshow</h1>
    </div>
    <div id="login" >
        <?

        echo $this->form;

        ?>
    </div>
</div>