<?php
echo $this->headScript()->
        appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
        appendFile($this->baseUrl() . "/js/bootstrap/bootstrap.js")->
        appendFile($this->baseUrl() . "/js/jquery.validate.js");

echo $this->headLink()
        ->setIndent('  ')
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap.css")
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap-responsive.css");
?>



<?
if(isset($this->errorMessage)){

            echo $this->errorMessage;

}?>

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
    <title>WebAsistencia UCA</title>
    <style>
        tr,td{
            padding: 10px;
        }
        #logo{margin: 20px;}
        a{
            text-align: right;
            text-decoration: none;
            font-size: 10px;
            color: #49AFCD;
            top: 0;
            float: right;
        }
        #forgot{
            margin: 0;
            padding: 0;
            font-size:11px;
            height: 11px;
            line-height: 11px;
        }
    </style>

</head>
   <p style="margin-left: 50px;" class="navbar-text pull-right"><a href="/administration/logout">Cerrar Sesion</a></p>

    <div class="span5"></div>
        <div class="span3" style="margin: 30px;">
            <div id="logo">   
                <h1>Registro</h1>
            </div>        <div id="registro-user">
            <form id="register-form" class="form-horizontal" action="<?php echo $this->url(array('controller' => 'register', 'action' => 'signup')); ?>" method="post">
                <?echo $this->form;?>                
        </div>
        </div>
    <div class="span3"></div>
       