<?php
echo $this->headScript()
        ->appendFile($this->baseUrl() . "/js/jquery-1.10.2.min.js")
        ->appendFile($this->baseUrl() . "/js/typeahead.min.js")
        ->appendFile($this->baseUrl() . "/js/hogan-2.0.0.js");

echo $this->headLink()
        ->setIndent('  ')
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap.css")
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap-responsive.css")
        ->prependStylesheet($this->baseUrl() . "/css/typeahead.css");
?>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
    <title>Asistencia UCA</title>
    <style>
        tr,td{
            padding: 10px;
        }
        #logo{margin: 20px;}
        a{
            text-align: right;
            text-decoration: none;
            font-size: 12px;
            font-weight:bold;
            color: #49AFCD;
            top: 0;
            float: right;
        }
        #forgot{
            margin: 0;
            padding: 0;
            font-size:11px;
            height: 11px;
            line-height: 11px;
        }
    </style>

    <script type="text/javascript">
        $(document).ready(function() {
            var list = [];
            var json;

            $.ajax({
                url: "../administration/getteachers",
                success: function(data) {
                    json = data;
                    for (var i = 0; i < data.length; i++) {
                        if (list.indexOf(data[i].email) === -1)
                            list.push(data[i].email);
                    }
                },
                dataType: 'json',
                async: false
            });

            $('#username').typeahead({
                name: 'profesor',
                local: list
            });

            $('#username').blur(function() {
                var email = $('#username').val();
                $('#materia').empty();
                var data = json;

                for (var i = 0; i < data.length; i++) {
                    if (data[i].email === email) {
                        $('#materia').append('<option value="' + data[i].id_materia + '">' + data[i].nombre_materia + '</option>');
                    }
                }
            });

        });
    </script>

</head>
<div class="span3" style="margin: 0px;">
    <div id="logo">   
        <h1>Marcación</h1>
    </div>
    <div id="login" >

        <form id="login-form" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'asistenciaprofesores')); ?>" method="post">
            <table>
                <tr><td>Usuario</td><td><input type="text" id="username" name="username"></td></tr>
                <tr><td>Materias</td><td><select name="materia" id="materia">
                </select>
                </tr>
                <tr><td></td><td>
                                        <input type="submit" id="submit">

                <!--<a onclick="doSubmit();" href="#" class="btn btn-primary" id="login-btn"> <i class="icon-hand-right icon-white"></i>Marcar</a></td>-->

                    <?php echo $this->loginError; ?>
            </table>
        </form>
    </div>
</div>
<div class="span3"></div>
