<?php
echo $this->headScript()->
        appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
        appendFile($this->baseUrl() . "/js/bootstrap/bootstrap.js");

echo $this->headLink()
        ->setIndent('  ')
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap.css")
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap-responsive.css");
?>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
    <title>Asistencia UCA</title>
    <style>
        tr,td{
            padding: 10px;
        }
        #logo{margin: 20px;}
        a{
            text-align: right;
            text-decoration: none;
            font-size: 12px;
            font-weight:bold;
            color: #49AFCD;
            top: 0;
            float: right;
        }
        #forgot{
            margin: 0;
            padding: 0;
            font-size:11px;
            height: 11px;
            line-height: 11px;
        }
    </style>

    <script type="text/javascript">
        function hideAlert() {
            $("#value-alert").hide(1000);
        }

        function doSubmit() {
            $("#login-form").submit();
        }

        $(document).ready(function() {
            setTimeout("hideAlert()", 7500);

//            $("#login-btn").click(function(event) {
//                doSubmit();
//            });

            $("#login-form").validate({
                rules: {
                    username: {
                        required: true
                    },
                    password: {
                        required: true
                    }
                },
                messages: {
                    username: "Username requerido",
                    password: "Password requerido"
                }
            });
        });
    </script>

</head>
<div class="span6" style="margin: 0px;">
    <div id="logo">   
        
        <h1>Sistema de Marcación</h1>
    </div>
    <div id="login" >
                   ACA VA LA TABLA CON EL LISTADO DE LAS MARCACIONES DE LOS FUNCIONARIOS
                    <?php echo $this->loginError; ?>
    </div>
</div>
<div class="span3"></div>