<?php
echo $this->headScript()->
        appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
        appendFile($this->baseUrl() . "/js/bootstrap/bootstrap.js");

echo $this->headLink()
        ->setIndent('  ')
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap.css")
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap-responsive.css");
?>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
    <title>Asistencia UCA</title>
    <style>
        tr,td{
            padding: 10px;
        }
        #logo{margin: 20px; padding: auto; text-align: center}
        a{
            text-align: right;
            text-decoration: none;
            font-size: 12px;
            font-weight:bold;
            color: #49AFCD;
            top: 0;
            float: right;
        }
        #forgot{
            margin: 0;
            padding: 0;
            font-size:11px;
            height: 11px;
            line-height: 11px;
        }
    </style>

    <script type="text/javascript">
        function hideAlert() {
            $("#value-alert").hide(1000);
        }

        function doSubmit() {
            $("#login-form").submit();
        }

        $(document).ready(function() {
            setTimeout("hideAlert()", 7500);

//            $("#login-btn").click(function(event) {
//                doSubmit();
//            });

            $("#login-form").validate({
                rules: {
                    username: {
                        required: true
                    },
                    password: {
                        required: true
                    }
                },
                messages: {
                    username: "Username requerido",
                    password: "Password requerido"
                }
            });
        });
    </script>

</head>
    <div id="logo">   
        <h1>Listado de Marcación</h1>
    </div>
        <table class="container table table-striped table-bordered">
                    <?php
                    $firsttime = true;
                    foreach ($this->marcaciones as $key => $marcacion)
                   {
                        if($firsttime){
                            $firsttime = false;
                            ?><tr><?php
                            foreach($marcacion as $campo => $valor){
                                ?><th><?php echo $campo ?></th><?php
                            }
                            ?></tr><?php
                        }
                        
                       ?><tr><?php
                           foreach($marcacion as $campo => $valor){
                             ?><td><?php echo $valor ?></td>
                        <?php
                           }
                       ?></tr><?php
                   } ?>
        </table>
<div class="span3"></div>