<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<?php
$this->setEncoding('UTF-8');

echo $this->headLink()
        ->setIndent('  ')
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap.css")
        ->prependStylesheet($this->baseUrl() . "/css/bootstrap/bootstrap-responsive.css")
        ->prependStylesheet($this->baseUrl() . "/css/jquery-ui-1.8.23.custom.css")
        ->prependStylesheet($this->baseUrl() . "/css/dt-bootstrap/DT_bootstrap.css");
?>

<head>
    <meta charset="utf-8"/>
    <title>WebAsistencia UCA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
            .sidebar-nav {
                padding: 9px 0;
            }
        </style>

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li><a href="<?php echo $this->baseUrl() . "/index/asistenciafuncionarios" ?>"></i>Asistencia Funcionarios</a></li>    
                            <li><a href="<?php echo $this->baseUrl() . "/index/asistenciaprofesores" ?>"></i>Asistencia Profesores</a></li>    
                            <li><a href="<?php echo $this->baseUrl() . "/recuperaciones" ?>"></i>Recuperación de Clase</a></li>    
                            <li><a href="<?php echo $this->baseUrl() . "/administration/index" ?>"></i>Registrar Nuevo Usuario</a></li>    
                         </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span2"></div><!--/span-->
            <div class="span8">

                <div class="row-fluid">
                    <?php
                    echo $this->layout()->content;
                    ?>

                </div>

            </div><!--/row-->
            <div class="span2"></div>
        </div><!--/span-->
    </div><!--/row-->

</body>